name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build APK with Gradle
      run: ./gradlew assembleDebug

    - name: Upload release APK
      uses: actions/upload-artifact@v3
      with:
        name: 1p-browsercompat-debug
        path: ./app/build/outputs/apk/debug/app-debug.apk

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./app/build/outputs/apk/debug/app-debug.apk
